include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  exclude:
    - "bin/cache/**"
    - "**/*.g.dart"
    - "**/*.mocks.dart"

enable-experiment:
  - extension-services

linter:
  rules:
    # adopted from pedantic
    omit_local_variable_types: true

    # adopted from pedantic
    always_declare_return_types: true

    # adopted from pedantic
    prefer_single_quotes: true

    # Reasoning: futures create non-linear control flow and that should be apparent to the reader.
    unawaited_futures: true

    # Reasoning: we rarely use dart doc in the way parameter renaming would create an issue.
    avoid_renaming_method_parameters: false

    # Reasoning: nearly none of our widgets are keyed, so this adds noise to the constructors.
    use_key_in_widget_constructors: false

    # Reasoning: adjacent strings are easily confused with separate elements in a list literal.
    no_adjacent_strings_in_list: true

    # Reasoning: avoid mutability when possible.
    prefer_final_locals: true

    # TODO migrate to always_use_package_imports
    prefer_relative_imports: true

    # Reasoning: keep the pubspec dependency list tidy.
    sort_pub_dependencies: true
