targets:
  $default:
    builders:
      # Typically the builder key is just the package name, run `pub run build_runner doctor` to check your config.
      mockito:mockBuilder:
        generate_for:
          # Example glob for only the Dart files under `lib/models`
          - test/**/*.dart
          - test/*.dart
          - bin/*.dart
          - bin/**/*.dart
      built_value_generator:built_value:
        generate_for:
          - lib/models/*.dart
          - lib/models/**/*.dart
