name: gutlogic
description: Gut Logic app

# Prevent accidentally publishing the package to pub.dev
publish_to: "none"

version: 1.1.0

environment:
  sdk: ^2.13.0
  flutter: ^2.5.0

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^5.1.0
  built_value: ^8.0.6
  crypto: ^3.0.0
  datetime_picker_formfield: ^2.0.0
  device_info_plus: ^2.1.0
  email_validator: ^2.0.1
  equatable: ^2.0.0
  flutter_password_strength: ^0.1.6
  flutter_sfsymbols: ^2.0.0
  flutter_speed_dial: ^5.0.0+1
  flutter_svg: ^1.0.3
  gap: ^2.0.0
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.1
  intl: 0.17.0
  logger: ^1.0.0
  material_design_icons_flutter: 5.0.5955-rc.1
  package_info_plus: ^1.0.4
  rxdart: ^0.27.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  url_launcher: ^6.0.2

  # Bloc
  bloc_concurrency: ^0.1.0
  flutter_bloc: ^7.2.0

  # Utility
  provider: ^6.0.0
  quiver: ^3.0.1

  # Firebase
  cloud_firestore: ^2.5.1
  cloud_functions: ^3.2.4
  firebase_analytics: ^8.3.1
  firebase_auth: ^1.1.2
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_remote_config: ^0.10.0+5
  firebase_dynamic_links: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

  test: any
  bloc_test: ^8.0.0
  build_runner: ^2.0.2
  built_value_generator: ^8.0.6
  fake_cloud_firestore: ^1.1.0
  effective_dart: ^1.3.1
  flutter_launcher_icons: ^0.9.0
  mockito: ^5.0.7
  mocktail: ^0.1.2
  timezone: ^0.7.0
  path: ^1.7.0
  yaml: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# To generate icons, run `flutter pub run flutter_launcher_icons:main`
flutter_icons:
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  image_path: "assets/app_icon/logo_green.png"
  # image_path_android: "assets/logo_green.png"
  # image_path_ios: "assets/logo_green.png"
  adaptive_icon_background: "assets/app_icon/logo_android_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/app_icon/logo_android_foreground.png" # only available for Android 8.0 devices and above

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/auth/apple/
    - assets/auth/google/
    - assets/consent/
    - assets/pain_scale/
    - assets/icons/

  fonts:
    - family: SickFaceFont
      fonts:
        - asset: assets/icons/SickFaceFont.ttf
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
        - asset: assets/fonts/SF-Pro-Italic.ttf
          style: italic
    - family: Quicksand410
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght-410.ttf
    - family: Quicksand420
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght-420.ttf
    - family: Quicksand430
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght-430.ttf
    - family: Quicksand440
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght-440.ttf
    - family: Quicksand450
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght-450.ttf
    - family: Quicksand460
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght-460.ttf
    - family: Quicksand470
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght-470.ttf
    - family: Quicksand480
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght-480.ttf
    - family: Quicksand490
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght-490.ttf
