AWSTemplateFormatVersion: 2010-09-09


Resources:

  GutAITable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: nameId
          AttributeType: S
        - 
          AttributeName: entryId
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: nameId
          KeyType: HASH
        - 
          AttributeName: entryId
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: GutAITable




  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: gut-ai-appsync-dynamodb-role
      ManagedPolicyArns:
        - Ref: AppSyncDynamoDBPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
    DependsOn:
      - AppSyncDynamoDBPolicy

  AppSyncDynamoDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy to allow AWS AppSync to access the tables created by this template.
      Path: /appsync/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
            Resource: !Join [ "", [ !GetAtt GutAITable.Arn, "*" ] ]

  AppSyncAPI:
    Type: AWS::AppSync::GraphQLApi
    Properties: 
      AuthenticationType: API_KEY
      Name: GutAIAppSync

  
  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties: 
      ApiId: !GetAtt AppSyncAPI.ApiId
      DefinitionS3Location: schema.graphql


  AppSyncDataSource:
    Type: AWS::AppSync::DataSource    
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      Name: GutAITable
      Description: The Gut AI DynamoDB table in us-east-1
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt DynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref GutAITable
        AwsRegion: !Sub ${AWS::Region}

# Food Resolvers

  AppSyncListFoodsQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Query
      FieldName: listFoods
      DataSourceName: !GetAtt AppSyncDataSource.Name
      RequestMappingTemplateS3Location: resolver/food/listFoodsRequest.vtl
      ResponseMappingTemplate: "$util.toJson($context.result)"

  AppSyncGetFoodQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Query
      FieldName: getFood
      DataSourceName: !GetAtt AppSyncDataSource.Name
      RequestMappingTemplateS3Location: resolver/food/getFoodRequest.vtl
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncCreateFoodMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Mutation
      FieldName: createFood
      DataSourceName: !GetAtt AppSyncDataSource.Name
      RequestMappingTemplateS3Location: resolver/food/createFoodRequest.vtl
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncUpdateFoodMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Mutation
      FieldName: updateFood
      DataSourceName: !GetAtt AppSyncDataSource.Name
      RequestMappingTemplateS3Location: resolver/food/updateFoodRequest.vtl
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncDeleteFoodMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Mutation
      FieldName: deleteFood
      DataSourceName: !GetAtt AppSyncDataSource.Name
      RequestMappingTemplateS3Location: resolver/food/deleteFoodRequest.vtl
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

# Meal Entry Resolvers

  AppSyncListMealEntriesQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Query
      FieldName: listMealEntries
      DataSourceName: !GetAtt AppSyncDataSource.Name
      RequestMappingTemplateS3Location: resolver/mealEntry/listMealEntriesRequest.vtl
      ResponseMappingTemplate: "$util.toJson($context.result)"

  AppSyncGetMealEntryQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Query
      FieldName: getMealEntry
      DataSourceName: !GetAtt AppSyncDataSource.Name
      RequestMappingTemplateS3Location: resolver/mealEntry/getMealEntryRequest.vtl
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncCreateMealEntryMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Mutation
      FieldName: createMealEntry
      DataSourceName: !GetAtt AppSyncDataSource.Name
      RequestMappingTemplateS3Location: resolver/mealEntry/createMealEntryRequest.vtl
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncUpdateMealEntryMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Mutation
      FieldName: updateMealEntry
      DataSourceName: !GetAtt AppSyncDataSource.Name
      RequestMappingTemplateS3Location: resolver/mealEntry/updateMealEntryRequest.vtl
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  AppSyncDeleteMealEntryMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Mutation
      FieldName: deleteMealEntry
      DataSourceName: !GetAtt AppSyncDataSource.Name
      RequestMappingTemplateS3Location: resolver/mealEntry/deleteMealEntryRequest.vtl
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

Outputs:
  GutAITableName:
    Description: The name of the DynamoDB Table
    Value: !Ref GutAITable
  GraphQLApiEndpoint:
    Description: The URL to the GraphQL Endpoint
    Value: !GetAtt AppSyncAPI.GraphQLUrl
  GraphQLApiId:
    Description: The API ID of the GraphQL API
    Value: !GetAtt AppSyncAPI.ApiId