AWSTemplateFormatVersion: 2010-09-09


Resources:

  GutAITable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: pk
          AttributeType: S
        - 
          AttributeName: sk
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: pk
          KeyType: HASH
        - 
          AttributeName: sk
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: GutAITable


  AppSyncAPI:
    Type: AWS::AppSync::GraphQLApi
    Properties: 
      AuthenticationType: API_KEY
      Name: AppSyncAPI

  
  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties: 
      ApiId: !GetAtt AppSyncAPI.ApiId
      DefinitionS3Location: schema.graphql


  AppSyncDataSource:
    Type: AWS::AppSync::DataSource    
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      Name: GutAITable
      Description: The Gut AI DynamoDB table in us-east-1
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: "arn:aws:iam::YOUR_ACCOUNT_ID:role/AppSyncTutorialAmazonDynamoDBRole"
      DynamoDBConfig:
        AwsRegion: "us-east-1"
        TableName: GutAITable