locales:
  - en-US

devices:
  android:
  # TODO add necessary android devices
  ios:
    - iPhone 8 Plus # 5.5 inch
    - iPhone 12 Pro Max # 6.5 inch
    - iPad Pro (12.9-inch) (4th generation)
    - iPad Pro (12.9-inch) (2nd generation)
