.client-merge-request-rules:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      changes: [client/**/*]
    - if: $CI_MERGE_REQUEST_ID
      allow_failure: true
      when: manual

.client-develop-commit-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      changes: [client/**/*]
    - if: $CI_COMMIT_BRANCH == "develop"
      allow_failure: true
      when: manual

.client-release-commit-rules:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release/
      changes: [client/**/*]
    - if: $CI_COMMIT_BRANCH =~ /^release/
      allow_failure: true
      when: manual

.client-cache: &client-cache
  key:
    files:
      - client/pubspec.lock
      - client/ios/Gemfile.lock
  paths:
    - client/.pub-cache
    - client/.dart_tool/package_config.json
    - client/build/ios/archive/Runner.xcarchive
    - client/ios/vendor/bundle

.client:
  image: cirrusci/flutter:3.0.5
  tags:
    - docker
  before_script:
    - shopt -s expand_aliases
    # move into the client directory
    - cd client
    # configure pub to use a local cache directory
    - export PUB_CACHE=./.pub-cache
    # alias flutter to use fvm
    - if [ -x "$(command -v fvm)" ]; then
      echo "Using FVM";
      fvm install;
      alias flutter="fvm flutter";
      fi;
    # print the flutter version for logs
    - flutter --version
    # install dependencies
    - flutter pub get
  cache:
    <<: *client-cache
    policy: pull

client:prep:
  stage: prep
  extends:
    - .client
  script:
    # write the app version into the pipeline dotenv file (https://gitlab.com/gitlab-org/gitlab-runner/-/issues/6400)
    - echo "FLUTTER_APP_VERSION=$(flutter pub run bin/version)" > version.env
    # build autogenerated dart files (models, etc) for artifacts export
    - flutter pub run build_runner build --delete-conflicting-outputs
  rules:
    - !reference [.client-develop-commit-rules, rules]
    - !reference [.client-release-commit-rules, rules]
    - !reference [.client-merge-request-rules, rules]
  artifacts:
    reports:
      dotenv: client/version.env
    paths:
      - client/lib/**/*.g.dart
      - client/test/**/*.mocks.dart
      - client/bin/**/*.mocks.dart
    expire_in: 1 day
  cache:
    <<: *client-cache
    policy: pull-push

# client:svgo:
#   stage: prep
#   image: node-alpine
#   before_script:
#     - npm i -g svgo
#   script:
#     - svgo -rf . .
#   rules:
#     - !reference [.client-develop-commit-rules, rules]
#     - !reference [.client-release-commit-rules, rules]
#     - !reference [.client-merge-request-rules, rules]
#   artifacts:
#     paths:
#       - client/**/*.svg
#     expire_in: 1 day
#   cache:
#     key:
#       files:
#         - client/pubspec.lock
#     paths:
#       - client/**/*.svg
#     policy: push

client:lint:
  stage: test
  extends:
    - .client
  script:
    - flutter analyze --fatal-warnings lib test
    # Delete generated files after analysis but before formatting. They cause the formatter to quit with an error
    # because they are formatter to 80 columns. There's no way to change the source_gen formatting, and no way to
    # exclude the generated files, so we have to delete them (see https://github.com/dart-lang/dart_style/issues/864).
    - find lib test bin -name "*.g.dart" -type f -delete
    - find lib test bin -name "*.mocks.dart" -type f -delete
    - flutter format --line-length 120 --dry-run --set-exit-if-changed lib test
  rules:
    - !reference [.client-develop-commit-rules, rules]
    - !reference [.client-release-commit-rules, rules]
    - !reference [.client-merge-request-rules, rules]
  dependencies:
    - client:prep
  allow_failure: true

client:test:
  stage: test
  extends:
    - .client
  script:
    - bash test/generate_coverage_test_file.sh
    - flutter test --coverage
    - lcov --list coverage/lcov.info
    - genhtml coverage/lcov.info -o coverage/html
  artifacts:
    paths:
      - client/coverage
    expire_in: 5 days
  rules:
    - !reference [.client-develop-commit-rules, rules]
    - !reference [.client-release-commit-rules, rules]
    - !reference [.client-merge-request-rules, rules]
  dependencies:
    - client:prep

# build:client:apk:
#   stage: build
#   extends:
#     - .client
#   script:
#     - flutter build apk --flavor $FLUTTER_FLAVOR --release --no-codesign
#   rules:
#     - *client-merge-request-rule
#     - *manual-commit-rule

client:build:ios:
  stage: build
  extends:
    - .client
  tags:
    - macos
  script:
    - pod repo update
    # prep fastlane
    - cd ios
    - gem install --user-install bundler
    - bundle install
    - bundle exec fastlane run increment_build_number build_number:"$CI_PIPELINE_ID"
    - flutter pub run flutter_launcher_icons:main
    - flutter build ios --flavor $FLUTTER_FLAVOR --release --build-number=$CI_PIPELINE_ID --no-codesign
  rules:
    - !reference [.client-merge-request-rules, rules]
    - !reference [.client-develop-commit-rules, rules]
    - !reference [.client-release-commit-rules, rules]
  cache:
    <<: *client-cache
    policy: pull-push
  dependencies:
    - client:prep

client:screenshots:
  stage: predeploy
  extends:
    - .client
  tags:
    - macos
  script:
    # generate screenshots
    - flutter pub run bin/screenshots
    # prep fastlane
    - cd ios/fastlane
    - gem install --user-install bundler
    - bundle install
    # place screenshots into frames
    - bundle exec fastlane frameit download_frames
    - bundle exec fastlane frames
    # remove screenshots without frames so they aren't uploaded to App Store
    - cd screenshots
    - find . -type f ! -name '*_framed.*' -delete
  artifacts:
    paths:
      - client/android/fastlane
      - client/ios/fastlane
    expire_in: 1 day
  rules:
    - !reference [.client-release-commit-rules, rules]
    - if: $CI_MERGE_REQUEST_ID
      allow_failure: true
      when: manual
  dependencies:
    - client:prep

.client:deploy:ios:
  stage: deploy
  extends:
    - .client
  tags:
    - macos
  script:
    # copy GOOGLE_APPLICATION_CREDENTIALS from environment into fastlane target
    - cd ios
    - cp "$GOOGLE_APPLICATION_CREDENTIALS" "$(pwd)/gc_keys.json"
    # prep fastlane
    - cd fastlane
    - gem install --user-install bundler
    - bundle install
    - bundle exec fastlane $FASTLANE_CHANNEL
  dependencies:
    - client:build:ios

client:deploy:develop:ios:
  extends:
    - .client:deploy:ios
  rules:
    - !reference [.client-develop-commit-rules, rules]
  dependencies:
    - client:build:ios
  environment: develop

client:deploy:staging:ios:
  stage: deploy
  extends:
    - .client:deploy:ios
  variables:
    FLUTTER_FLAVOR: production
    FASTLANE_CHANNEL: staging
  release:
    tag_name: "v$FLUTTER_APP_VERSION-b$CI_PIPELINE_ID"
    description: "Release v$FLUTTER_APP_VERSION-b$CI_PIPELINE_ID"
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release/
      when: manual
  dependencies:
    - client:build:ios
  environment: staging

client:deploy:release:ios:
  stage: deploy
  extends:
    - .client:deploy:ios
  variables:
    FLUTTER_FLAVOR: production
    FASTLANE_CHANNEL: release
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release/
      when: manual
  dependencies:
    - client:build:ios
    - client:screenshots
  environment: release
